image:
  name: atlassian/default-image:2

test: &test
  step:
    name: Build and Test
    script:
    - export DEBUG=true
    - apt-get update && apt-get install -y bats
    - export DOCKERHUB_IMAGE='bitbucketpipelines/azure-storage-deploy'
    - export DOCKERHUB_TAG=${BITBUCKET_BUILD_NUMBER}
    - echo "Building image..."
    - docker build -t ${DOCKERHUB_IMAGE}:${DOCKERHUB_TAG} .
    - echo "Testing image..."
    - test/test.bats
    services:
    - docker

git_tag: &git_tag
  step:
    name: Git Tag
    script:
    - ./ci-scripts/git-setup.sh
    - ./ci-scripts/git-tag.sh

git_merge: &git_merge
  step:
    name: Git Merge
    script:
    - ./ci-scripts/git-setup.sh
    - ./ci-scripts/git-merge.sh

docker_release: &docker_release
  step:
    name: Build, Tag and Push Docker Image
    services:
    - docker
    script:
    - ./ci-scripts/docker-release.sh bitbucketpipelines/azure-storage-deploy

pipelines:
  default:
  - <<: *test

  branches:
    master:
    - <<: *test
    - <<: *git_tag
    - <<: *docker_release
    - <<: *git_merge

    release-*:
    - <<: *test
    - <<: *git_tag
    - <<: *docker_release
    - <<: *git_merge

    qa-*:
    - <<: *test
    - <<: *git_tag
    - <<: *docker_release

  custom:
    test-and-report:
    - step:
        script:
        - apt-get update && apt-get install -y bats
        - export DOCKERHUB_IMAGE='bitbucketpipelines/azure-storage-deploy'
        - export DOCKERHUB_TAG=${BITBUCKET_BUILD_NUMBER}
        - echo "Building image..."
        - docker build -t ${DOCKERHUB_IMAGE}:${DOCKERHUB_TAG} .
        - echo "Testing image..."
        - set +e
        - test/test.bats; test_exit_code=$?
        - set -e
        - echo test_exit_code = $test_exit_code
        - task: atlassian/report-task-test-result:1.0.0
          environment:
            DATADOG_API_KEY: $DATADOG_API_KEY
            TASK_NAME: azure-storage-deploy
            TEST_EXIT_CODE: $test_exit_code
        - exit $test_exit_code
        services:
        - docker
